version: '3'

services:
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
  
  adminer:
    depends_on:
      - db 
    image: adminer
    restart: always
    ports:
      - 8080:8080