version: '3'

services:
  server:
    image: alpine:latest
    working_dir: /server
    entrypoint: /server/bin
    volumes:
      - ./target/release/:/server/
    ports:
      - 8000:8000

  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: example
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080